name: NexusCore
main: dev.sergeantfuzzy.NexusCore.Main
version: ${project.version}
api-version: '1.21'
load: POSTWORLD
authors:
  - SergeantFuzzy
description: Core framework plugin powering NexusCore features — provides commands, GUI menus, and utilities for managing server systems and modules.

commands:
  nexus:
    description: NexusCore administration root command
    usage: /nexus [reload|version]
    aliases: [nc, ncore, nexuscore]
  feed:
    description: Feed yourself or another player. Use /feed status or /feed <player>.
    usage: /feed [status|<player>]
    aliases: [food, hunger]
    permission: nexuscore.feed
  heal:
    description: Heal yourself or another player.
    usage: /heal [<player>]
    permission: nexuscore.heal
  health:
    description: View health for yourself or others. Use /health status [player].
    usage: /health [status] [player]
    permission: nexuscore.health
  fly:
    description: Toggle or set flight. /fly [on|off] [player], /fly status [player]
    usage: /fly [on|off] [player]|status [player]
    permission: nexuscore.fly
  jump:
    description: Jump to the block you are looking at or make another player jump.
    usage: /jump [player]
    permission: nexuscore.jump
  randomtp:
    description: Randomly teleport to a safe location (or teleport another player).
    usage: /randomtp [player]
    aliases: [rtp]
    permission: nexuscore.randomtp
  spawn:
    description: Teleport to spawnpoint if set.
    usage: /spawn [player|reset|set]
    permission: nexuscore.spawn
  tp:
    description: Teleport to target player.
    usage: /tp [player]
    aliases: teleport
    permission: nexuscore.tp
  back:
    description: Return to your previous location.
    usage: /back [player]
    permission: nexuscore.back
  abilities:
    description: Open the Nexus abilities menu or activate an ability.
    usage: /abilities [menu|list|info <ability>|use <ability>]
    aliases: [ability, skills]
    permission: nexuscore.abilities

permissions:
  nexuscore.*:
    description: Grants access to all NexusCore commands and features.
    default: op
    children:
      nexuscore.admin.*: true
      nexuscore.abilities.*: true
      nexuscore.update.notify: true
  nexuscore.admin.*:
    description: Grants access to all NexusCore admin commands.
    default: op
    children:
      nexuscore.admin.reload: true
      nexuscore.version: true
      nexuscore.spawn: true
      nexuscore.spawn.reset: true
      nexuscore.spawn.set: true
      # Essentials admin (others) permissions
      nexuscore.feed.others: true
      nexuscore.heal.others: true
      nexuscore.health.others: true
      nexuscore.fly.others: true
      nexuscore.jump.others: true
      nexuscore.randomtp.others: true
      nexuscore.spawn.player: true
      nexuscore.tp.other: true
      nexuscore.back: true
      nexuscore.back.others: true
      nexuscore.abilities.*: true
  nexuscore.admin.reload:
    description: Allows use of /nexusreload.
    default: op
  nexuscore.update.notify:
    description: Receive in-game update notifications on join.
    default: op

  # Self permissions
  nexuscore.feed:
    default: true
  nexuscore.heal:
    default: true
  nexuscore.health:
    default: true
  nexuscore.fly:
    default: true
  nexuscore.jump:
    default: true
  nexuscore.randomtp:
    default: true
  nexuscore.spawn:
    default: op
  nexuscore.spawn.reset:
    default: op
  nexuscore.spawn.set:
    default: op
  nexuscore.tp:
    default: true
  nexuscore.tphere:
    default: true
  nexuscore.back:
    default: true
  nexuscore.abilities:
    default: true
  nexuscore.abilities.gui:
    default: true
  nexuscore.abilities.use.*:
    default: op
    children:
      nexuscore.abilities.use.berserk: true
      nexuscore.abilities.use.guardian_shell: true
      nexuscore.abilities.use.blink: true
      nexuscore.abilities.use.regrowth: true
      nexuscore.abilities.use.shockwave: true
      nexuscore.abilities.use.inferno: true
      nexuscore.abilities.use.frost_nova: true
      nexuscore.abilities.use.feather_fall: true
      nexuscore.abilities.use.energize: true
      nexuscore.abilities.use.lifeline: true
      nexuscore.abilities.use.stone_skin: true
      nexuscore.abilities.use.wind_step: true
      nexuscore.abilities.use.thunderclap: true
      nexuscore.abilities.use.verdant: true
      nexuscore.abilities.use.night_stalker: true
      nexuscore.abilities.use.arctic_aura: true
      nexuscore.abilities.use.flame_dash: true
      nexuscore.abilities.use.arcane_pulse: true
      nexuscore.abilities.use.miners_focus: true
      nexuscore.abilities.use.gravity_well: true
      nexuscore.abilities.use.radiant_heal: true
      nexuscore.abilities.use.rift_recall: true
      nexuscore.abilities.use.tide_caller: true
      nexuscore.abilities.use.beastmaster: true
      nexuscore.abilities.use.earthshatter: true
      nexuscore.abilities.use.skybound_leap: true
      nexuscore.abilities.use.solar_flare: true

  # Others (admin) sub-perms
  nexuscore.feed.others:
    default: op
  nexuscore.heal.others:
    default: op
  nexuscore.health.others:
    default: op
  nexuscore.fly.others:
    default: op
  nexuscore.jump.others:
    default: op
  nexuscore.randomtp.others:
    default: op
  nexuscore.spawn.player:
    default: op
  nexuscore.tp.other:
    default: op
  nexuscore.back.others:
    default: op
  nexuscore.abilities.use.berserk:
    default: false
  nexuscore.abilities.use.guardian_shell:
    default: false
  nexuscore.abilities.use.blink:
    default: false
  nexuscore.abilities.use.regrowth:
    default: false
  nexuscore.abilities.use.shockwave:
    default: false
  nexuscore.abilities.use.inferno:
    default: false
  nexuscore.abilities.use.frost_nova:
    default: false
  nexuscore.abilities.use.feather_fall:
    default: false
  nexuscore.abilities.use.energize:
    default: false
  nexuscore.abilities.use.lifeline:
    default: false
  nexuscore.abilities.use.stone_skin:
    default: false
  nexuscore.abilities.use.wind_step:
    default: false
  nexuscore.abilities.use.thunderclap:
    default: false
  nexuscore.abilities.use.verdant:
    default: false
  nexuscore.abilities.use.night_stalker:
    default: false
  nexuscore.abilities.use.arctic_aura:
    default: false
  nexuscore.abilities.use.flame_dash:
    default: false
  nexuscore.abilities.use.arcane_pulse:
    default: false
  nexuscore.abilities.use.miners_focus:
    default: false
  nexuscore.abilities.use.gravity_well:
    default: false
  nexuscore.abilities.use.radiant_heal:
    default: false
  nexuscore.abilities.use.rift_recall:
    default: false
  nexuscore.abilities.use.tide_caller:
    default: false
  nexuscore.abilities.use.beastmaster:
    default: false
  nexuscore.abilities.use.earthshatter:
    default: false
  nexuscore.abilities.use.skybound_leap:
    default: false
  nexuscore.abilities.use.solar_flare:
    default: false
